"use client";

import { useState } from "react";
import { BookOpen, GraduationCap, MessageSquare, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Application, InterviewQuestion } from "@/lib/types/application";
import { generateInterviewPrep } from "@/lib/api/applications";

function QuestionList({
  title,
  icon: Icon,
  questions,
}: {
  title: string;
  icon: typeof MessageSquare;
  questions: InterviewQuestion[];
}) {
  return (
    <div className="space-y-3">
      <p className="flex items-center gap-2 text-sm font-semibold">
        <Icon className="size-4 text-muted-foreground" />
        {title}
      </p>
      <ol className="space-y-4">
        {questions.map((q, index) => (
          <li key={index} className="space-y-2 rounded-lg border p-3 sm:p-4">
            <p className="text-sm font-medium">
              {index + 1}. {q.question}
            </p>
            <ul className="space-y-1.5">
              {q.talkingPoints.map((point) => (
                <li
                  key={point}
                  className="flex gap-2 text-sm text-muted-foreground"
                >
                  <span className="mt-2 size-1 shrink-0 rounded-full bg-muted-foreground" />
                  <span>{point}</span>
                </li>
              ))}
            </ul>
          </li>
        ))}
      </ol>
    </div>
  );
}

// The Interview Prep Pack: likely questions + talking points grounded in
// the user's actual resume, generated by the two-node LangGraph pipeline
// in the AI service (ai-service/app/graph/interview_prep.py).
export function InterviewPrepCard({
  app,
  onUpdated,
}: {
  app: Application;
  onUpdated: (app: Application) => void;
}) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleGenerate() {
    setIsGenerating(true);
    setError(null);
    try {
      onUpdated(await generateInterviewPrep(app.id));
    } catch (err) {
      const message =
        (err as { response?: { data?: { message?: string } } })?.response
          ?.data?.message ??
        "Generation failed — is the AI service running?";
      setError(message);
    } finally {
      setIsGenerating(false);
    }
  }

  const prep = app.interviewPrep;

  return (
    <Card>
      <CardHeader className="flex flex-row flex-wrap items-center justify-between gap-2 space-y-0">
        <CardTitle>Interview prep</CardTitle>
        {prep && (
          <Button
            variant="outline"
            size="sm"
            onClick={handleGenerate}
            disabled={isGenerating}
          >
            <RefreshCw data-icon="inline-start" />
            {isGenerating ? "Regenerating..." : "Regenerate"}
          </Button>
        )}
      </CardHeader>
      <CardContent className="space-y-6">
        {!prep && (
          <div className="flex flex-col items-center gap-3 py-4 text-center">
            <GraduationCap className="size-6 text-muted-foreground" />
            <p className="max-w-md text-sm text-muted-foreground">
              Get likely interview questions for this role, with talking
              points drawn from your own resume — plus the gaps worth
              studying before the call.
            </p>
            <Button onClick={handleGenerate} disabled={isGenerating}>
              {isGenerating ? "Preparing..." : "Generate prep pack"}
            </Button>
            {isGenerating && (
              <p className="text-xs text-muted-foreground">
                Two-step pipeline (focus areas, then questions) — takes up
                to a minute on the local model.
              </p>
            )}
          </div>
        )}

        {prep && (
          <>
            <div className="space-y-1.5">
              <p className="text-xs font-medium text-muted-foreground">
                The interview will likely focus on
              </p>
              <div className="flex flex-wrap gap-1.5">
                {prep.focusAreas.map((area) => (
                  <Badge key={area} variant="secondary" className="h-auto whitespace-normal py-0.5 text-left">
                    {area}
                  </Badge>
                ))}
              </div>
            </div>

            {prep.gapsToPrepare.length > 0 && (
              <div className="space-y-1.5">
                <p className="flex items-center gap-2 text-xs font-medium text-muted-foreground">
                  <BookOpen className="size-3.5" />
                  Study before the interview
                </p>
                <ul className="space-y-1.5">
                  {prep.gapsToPrepare.map((gap) => (
                    <li key={gap} className="flex gap-2 text-sm">
                      <span className="mt-2 size-1 shrink-0 rounded-full bg-destructive" />
                      <span>{gap}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
              <QuestionList
                title="Technical questions"
                icon={MessageSquare}
                questions={prep.technicalQuestions}
              />
              <QuestionList
                title="Behavioral questions"
                icon={GraduationCap}
                questions={prep.behavioralQuestions}
              />
            </div>
          </>
        )}

        {error && <p className="text-sm text-destructive">{error}</p>}
      </CardContent>
    </Card>
  );
}
