import logging

from fastapi import Depends, FastAPI, Request
from fastapi.responses import JSONResponse

from app.core.config import settings
from app.core.security import require_service_token, warn_if_unprotected
from app.routers import (
    cover_letter,
    fit,
    interview_prep,
    resume,
)

# /docs, /redoc and /openapi.json are ON in local development and OFF
# whenever a SERVICE_TOKEN is configured — i.e. whenever this service is
# deployed somewhere public.
#
# They're generated by FastAPI outside any router, so the router-level
# token dependency below does not cover them: with the token set, they
# still answered 200 to anyone and published every endpoint's exact
# request and response schema — a map of the service the token exists to
# hide. Interactive docs are worth a lot locally and nothing in
# production, where the only client is our own backend.
_is_protected = bool(settings.service_token)

app = FastAPI(
    title="Job Assistant AI Service",
    docs_url=None if _is_protected else "/docs",
    redoc_url=None if _is_protected else "/redoc",
    openapi_url=None if _is_protected else "/openapi.json",
)

warn_if_unprotected()

# Each router lives in its own file under app/routers/ (one per endpoint) so
# this file stays pure wiring — no route logic here, just "which routes
# exist." When you add real parsing/scoring logic, it goes in the router
# files below, not here.
#
# The token check is attached here rather than inside each router for the
# same reason: whether an endpoint is reachable from outside is a wiring
# decision, and keeping it in one place means a new router can't be added
# unprotected by accident — you have to walk past these four lines.
protected = [Depends(require_service_token)]

app.include_router(resume.router, dependencies=protected)
app.include_router(fit.router, dependencies=protected)
app.include_router(cover_letter.router, dependencies=protected)
app.include_router(interview_prep.router, dependencies=protected)


# Deliberately NOT behind the token: Render's health check and the
# keep-warm pinger both hit this, and neither can hold a secret.
# It exposes nothing — see the handler.
@app.get("/health")
def health():
    return {"status": "ok"}


logger = logging.getLogger(__name__)


# Without this, an exhausted LLM quota reached the user as a bare 500,
# which NestJS then reported as "The AI service is unavailable right
# now" — true, but it sends you debugging the wrong thing entirely.
#
# The provider's exception class is deliberately NOT imported here. Every
# SDK we might use exposes the upstream HTTP status as .code or
# .status_code, so duck-typing keeps core/llm.py as the only file in this
# service that knows which provider is in play.
#
# NestJS passes any 4xx straight through with its detail intact (see
# OrchestrationService.toHttpException), so 429 arrives at the browser
# with this message rather than being flattened to a 502.
@app.exception_handler(Exception)
async def handle_unexpected_error(_request: Request, exc: Exception):
    status = getattr(exc, "code", None) or getattr(exc, "status_code", None)

    if status == 429:
        logger.warning("Upstream LLM rate limit hit: %s", exc)
        return JSONResponse(
            status_code=429,
            content={
                "detail": (
                    "The AI provider's rate limit was reached. "
                    "Please wait a minute and try again."
                )
            },
        )

    # Anything else is a genuine bug. Log the real cause, and still
    # answer with JSON shaped like every other error this service
    # returns, so the caller never has to parse an HTML error page.
    logger.exception("Unhandled error in AI service")
    return JSONResponse(
        status_code=500,
        content={"detail": "The AI service failed to process this request."},
    )
